### ISSUE TITLE
How to tell which puppet is being used

### ISSUE THREAD

**Issue by suntong** [wechaty/wechaty-puppet#89]
Hi, 

Of the different [Puppet Providers](https://github.com/wechaty/wechaty-puppet#providers), how can the wechaty script know which kind of puppet is being used? 

The reason I'm asking is that, for all the Emoji cleaning functions in [helper-functions/index.ts](https://github.com/wechaty/wechaty/blob/master/src/helper-functions/index.ts), they are actually puppet dependent. Knowing which puppet is being used can make the helper-functions generic. 

Thanks

**Comment by huan** [comment]
Thanks for asking this good question!

First, I agree with you that we need a way to get to know which puppet we are currently using with Wechaty.

This could be implemented by adding a new method to the puppet, let's say, named `name()`, so that it will return the puppet name:

```ts
const name = wechaty.puppet.name()
console.info(name)
// Output: wechaty-puppet-padplus
```

And when we are using the `wechaty-puppet-hostie`, it might be able to return the puppet provider behind it by returning `wechaty-puppet-hostie(wechaty-puppet-padplus)`?

Please feel free to let me know what you think about this design.

Secondly, I think all the puppet dependent API should not exist in Wechaty, which means the Wechaty should never care about what puppet it is using.

Can we get a way to remove all those `emoji` related methods from Wechaty to the puppet implementation? If we can do that, I believe that's the best way to solve your problem.

**Comment by suntong** [comment]
yeah, sure. good idea. 

One little add-on, when remove all those emoji related methods from Wechaty to the individual puppets, please keep the abstract function at puppets level, so they will be behaving the same when puppet is switched.

**Comment by huan** [comment]
Should be available after wechaty-puppet@0.23.4:

1. `puppet.name()` should give the NPM name of the puppet provider we are currently using.
1. `puppet.version()` is the NPM version of the puppet provider we are currently using.

**Comment by suntong** [comment]
Thanks a lot!

**Comment by huan** [comment]
You are welcome!

Todo: add an unit testing.

**Comment by huan** [comment]
Unit Testing added.
